// Liste des produits
const produits = [
    { id: 1, nom: 'KariteIDF.MariamD1',  description: 'Beure de karité 100% pur, Traitement naturel, filtrer et 100% Bio, Beurre local du Poro; Ingreien Le beurre de karité est composé principalement d#acides gras, de vitamines et de composants naturels. Les acides gras incluent l#acide oléique (40-60 %), qui hydrate et nourrit la peau, l#acide stéarique (20-50 %), qui stabilise la texture du beurre, l#acide linoléique (3-11 %), qui renforce la barrière cutanée, et l#acide palmitique (2-9 %), qui contribue à la texture onctueuse. Il contient également de la vitamine E, un antioxydant protégeant la peau, et de la vitamine A, qui favorise la régénération cellulaire. Parmi les composants naturels, on trouve l#allantoïne, qui apaise et répare la peau, les phytostérols, qui améliorent l#élasticité, les polyphénols, qui protègent des UV, et les triglycérides, qui hydratent et nourrissent. Le latex naturel est éliminé lors de la purification, et l#eau est présente en faible quantité, car le beurre de karité est anhydre.', prix: '2000', url:"./images/a1.jpg" },
    { id: 2, nom: 'KariteIDF.MariamD1',  description: 'Beure de karité 100% pur, Traitement naturel, filtrer et 100% Bio, Beurre local du Poro; Ingreien Le beurre de karité est composé principalement d#acides gras, de vitamines et de composants naturels. Les acides gras incluent l#acide oléique (40-60 %), qui hydrate et nourrit la peau, l#acide stéarique (20-50 %), qui stabilise la texture du beurre, l#acide linoléique (3-11 %), qui renforce la barrière cutanée, et l#acide palmitique (2-9 %), qui contribue à la texture onctueuse. Il contient également de la vitamine E, un antioxydant protégeant la peau, et de la vitamine A, qui favorise la régénération cellulaire. Parmi les composants naturels, on trouve l#allantoïne, qui apaise et répare la peau, les phytostérols, qui améliorent l#élasticité, les polyphénols, qui protègent des UV, et les triglycérides, qui hydratent et nourrissent. Le latex naturel est éliminé lors de la purification, et l#eau est présente en faible quantité, car le beurre de karité est anhydre.', prix: '2000', url:"./images/a2.jpg" },
    { id: 3, nom: 'KariteIDF.MariamD1',  description: 'Beure de karité 100% pur, Traitement naturel, filtrer et 100% Bio, Beurre local du Poro; Ingreien Le beurre de karité est composé principalement d#acides gras, de vitamines et de composants naturels. Les acides gras incluent l#acide oléique (40-60 %), qui hydrate et nourrit la peau, l#acide stéarique (20-50 %), qui stabilise la texture du beurre, l#acide linoléique (3-11 %), qui renforce la barrière cutanée, et l#acide palmitique (2-9 %), qui contribue à la texture onctueuse. Il contient également de la vitamine E, un antioxydant protégeant la peau, et de la vitamine A, qui favorise la régénération cellulaire. Parmi les composants naturels, on trouve l#allantoïne, qui apaise et répare la peau, les phytostérols, qui améliorent l#élasticité, les polyphénols, qui protègent des UV, et les triglycérides, qui hydratent et nourrissent. Le latex naturel est éliminé lors de la purification, et l#eau est présente en faible quantité, car le beurre de karité est anhydre.', prix: '2000', url:"./images/a3.jpg" },
    { id: 4, nom: 'KariteIDF.MariamD1',  description: 'Beure de karité 100% pur, Traitement naturel, filtrer et 100% Bio, Beurre local du Poro; Ingreien Le beurre de karité est composé principalement d#acides gras, de vitamines et de composants naturels. Les acides gras incluent l#acide oléique (40-60 %), qui hydrate et nourrit la peau, l#acide stéarique (20-50 %), qui stabilise la texture du beurre, l#acide linoléique (3-11 %), qui renforce la barrière cutanée, et l#acide palmitique (2-9 %), qui contribue à la texture onctueuse. Il contient également de la vitamine E, un antioxydant protégeant la peau, et de la vitamine A, qui favorise la régénération cellulaire. Parmi les composants naturels, on trouve l#allantoïne, qui apaise et répare la peau, les phytostérols, qui améliorent l#élasticité, les polyphénols, qui protègent des UV, et les triglycérides, qui hydratent et nourrissent. Le latex naturel est éliminé lors de la purification, et l#eau est présente en faible quantité, car le beurre de karité est anhydre.', prix: '2000', url:"./images/a4.jpg" },
    { id: 5, nom: 'KariteIDF.MariamD1',  description: 'Beure de karité 100% pur, Traitement naturel, filtrer et 100% Bio, Beurre local du Poro; Ingreien Le beurre de karité est composé principalement d#acides gras, de vitamines et de composants naturels. Les acides gras incluent l#acide oléique (40-60 %), qui hydrate et nourrit la peau, l#acide stéarique (20-50 %), qui stabilise la texture du beurre, l#acide linoléique (3-11 %), qui renforce la barrière cutanée, et l#acide palmitique (2-9 %), qui contribue à la texture onctueuse. Il contient également de la vitamine E, un antioxydant protégeant la peau, et de la vitamine A, qui favorise la régénération cellulaire. Parmi les composants naturels, on trouve l#allantoïne, qui apaise et répare la peau, les phytostérols, qui améliorent l#élasticité, les polyphénols, qui protègent des UV, et les triglycérides, qui hydratent et nourrissent. Le latex naturel est éliminé lors de la purification, et l#eau est présente en faible quantité, car le beurre de karité est anhydre.', prix: '2000', url:"./images/a5.jpg" },
    { id: 6, nom: 'PagneWIDF.MariamD1',  description: 'Beure de karité 100% pur, Traitement naturel, filtrer et 100% Bio, Beurre local du Poro; Ingreien Le beurre de karité est composé principalement d#acides gras, de vitamines et de composants naturels. Les acides gras incluent l#acide oléique (40-60 %), qui hydrate et nourrit la peau, l#acide stéarique (20-50 %), qui stabilise la texture du beurre, l#acide linoléique (3-11 %), qui renforce la barrière cutanée, et l#acide palmitique (2-9 %), qui contribue à la texture onctueuse. Il contient également de la vitamine E, un antioxydant protégeant la peau, et de la vitamine A, qui favorise la régénération cellulaire. Parmi les composants naturels, on trouve l#allantoïne, qui apaise et répare la peau, les phytostérols, qui améliorent l#élasticité, les polyphénols, qui protègent des UV, et les triglycérides, qui hydratent et nourrissent. Le latex naturel est éliminé lors de la purification, et l#eau est présente en faible quantité, car le beurre de karité est anhydre.', prix: '2000', url:"./images/a6.jpg" },
    { id: 7, nom: 'PagneWIDF.MariamD1',  description: 'Beure de karité 100% pur, Traitement naturel, filtrer et 100% Bio, Beurre local du Poro; Ingreien Le beurre de karité est composé principalement d#acides gras, de vitamines et de composants naturels. Les acides gras incluent l#acide oléique (40-60 %), qui hydrate et nourrit la peau, l#acide stéarique (20-50 %), qui stabilise la texture du beurre, l#acide linoléique (3-11 %), qui renforce la barrière cutanée, et l#acide palmitique (2-9 %), qui contribue à la texture onctueuse. Il contient également de la vitamine E, un antioxydant protégeant la peau, et de la vitamine A, qui favorise la régénération cellulaire. Parmi les composants naturels, on trouve l#allantoïne, qui apaise et répare la peau, les phytostérols, qui améliorent l#élasticité, les polyphénols, qui protègent des UV, et les triglycérides, qui hydratent et nourrissent. Le latex naturel est éliminé lors de la purification, et l#eau est présente en faible quantité, car le beurre de karité est anhydre.', prix: '2000', url:"./images/b1.jpg" },
    { id: 8, nom: 'PagneWIDF.MariamD1',  description: 'Beure de karité 100% pur, Traitement naturel, filtrer et 100% Bio, Beurre local du Poro; Ingreien Le beurre de karité est composé principalement d#acides gras, de vitamines et de composants naturels. Les acides gras incluent l#acide oléique (40-60 %), qui hydrate et nourrit la peau, l#acide stéarique (20-50 %), qui stabilise la texture du beurre, l#acide linoléique (3-11 %), qui renforce la barrière cutanée, et l#acide palmitique (2-9 %), qui contribue à la texture onctueuse. Il contient également de la vitamine E, un antioxydant protégeant la peau, et de la vitamine A, qui favorise la régénération cellulaire. Parmi les composants naturels, on trouve l#allantoïne, qui apaise et répare la peau, les phytostérols, qui améliorent l#élasticité, les polyphénols, qui protègent des UV, et les triglycérides, qui hydratent et nourrissent. Le latex naturel est éliminé lors de la purification, et l#eau est présente en faible quantité, car le beurre de karité est anhydre.', prix: '2000', url:"./images/b2.jpg" },
    { id: 9, nom: 'PagneWIDF.MariamD1',  description: 'Beure de karité 100% pur, Traitement naturel, filtrer et 100% Bio, Beurre local du Poro; Ingreien Le beurre de karité est composé principalement d#acides gras, de vitamines et de composants naturels. Les acides gras incluent l#acide oléique (40-60 %), qui hydrate et nourrit la peau, l#acide stéarique (20-50 %), qui stabilise la texture du beurre, l#acide linoléique (3-11 %), qui renforce la barrière cutanée, et l#acide palmitique (2-9 %), qui contribue à la texture onctueuse. Il contient également de la vitamine E, un antioxydant protégeant la peau, et de la vitamine A, qui favorise la régénération cellulaire. Parmi les composants naturels, on trouve l#allantoïne, qui apaise et répare la peau, les phytostérols, qui améliorent l#élasticité, les polyphénols, qui protègent des UV, et les triglycérides, qui hydratent et nourrissent. Le latex naturel est éliminé lors de la purification, et l#eau est présente en faible quantité, car le beurre de karité est anhydre.', prix: '2000', url:"./images/b3.jpg" },
    { id: 10, nom: 'PagneWIDF.MariamD1',  description: 'Beure de karité 100% pur, Traitement naturel, filtrer et 100% Bio, Beurre local du Poro; Ingreien Le beurre de karité est composé principalement d#acides gras, de vitamines et de composants naturels. Les acides gras incluent l#acide oléique (40-60 %), qui hydrate et nourrit la peau, l#acide stéarique (20-50 %), qui stabilise la texture du beurre, l#acide linoléique (3-11 %), qui renforce la barrière cutanée, et l#acide palmitique (2-9 %), qui contribue à la texture onctueuse. Il contient également de la vitamine E, un antioxydant protégeant la peau, et de la vitamine A, qui favorise la régénération cellulaire. Parmi les composants naturels, on trouve l#allantoïne, qui apaise et répare la peau, les phytostérols, qui améliorent l#élasticité, les polyphénols, qui protègent des UV, et les triglycérides, qui hydratent et nourrissent. Le latex naturel est éliminé lors de la purification, et l#eau est présente en faible quantité, car le beurre de karité est anhydre.', prix: '2000', url:"./images/b4.jpg" },
    { id: 11, nom: 'PagneWIDF.MariamD1',  description: 'Beure de karité 100% pur, Traitement naturel, filtrer et 100% Bio, Beurre local du Poro; Ingreien Le beurre de karité est composé principalement d#acides gras, de vitamines et de composants naturels. Les acides gras incluent l#acide oléique (40-60 %), qui hydrate et nourrit la peau, l#acide stéarique (20-50 %), qui stabilise la texture du beurre, l#acide linoléique (3-11 %), qui renforce la barrière cutanée, et l#acide palmitique (2-9 %), qui contribue à la texture onctueuse. Il contient également de la vitamine E, un antioxydant protégeant la peau, et de la vitamine A, qui favorise la régénération cellulaire. Parmi les composants naturels, on trouve l#allantoïne, qui apaise et répare la peau, les phytostérols, qui améliorent l#élasticité, les polyphénols, qui protègent des UV, et les triglycérides, qui hydratent et nourrissent. Le latex naturel est éliminé lors de la purification, et l#eau est présente en faible quantité, car le beurre de karité est anhydre.', prix: '2000', url:"./images/b5.jpg" },
    { id: 12, nom: 'PagneWIDF.MariamD1',  description: 'Beure de karité 100% pur, Traitement naturel, filtrer et 100% Bio, Beurre local du Poro; Ingreien Le beurre de karité est composé principalement d#acides gras, de vitamines et de composants naturels. Les acides gras incluent l#acide oléique (40-60 %), qui hydrate et nourrit la peau, l#acide stéarique (20-50 %), qui stabilise la texture du beurre, l#acide linoléique (3-11 %), qui renforce la barrière cutanée, et l#acide palmitique (2-9 %), qui contribue à la texture onctueuse. Il contient également de la vitamine E, un antioxydant protégeant la peau, et de la vitamine A, qui favorise la régénération cellulaire. Parmi les composants naturels, on trouve l#allantoïne, qui apaise et répare la peau, les phytostérols, qui améliorent l#élasticité, les polyphénols, qui protègent des UV, et les triglycérides, qui hydratent et nourrissent. Le latex naturel est éliminé lors de la purification, et l#eau est présente en faible quantité, car le beurre de karité est anhydre.', prix: '2000', url:"./images/b6.jpg" },
];

// Fonction pour obtenir les paramètres de l'URL
function getParametreUrl(nom) {
    const urlParams = new URLSearchParams(window.location.search);
    return urlParams.get(nom);
}

// Récupère l'identifiant du produit depuis l'URL
const produitId = parseInt(getParametreUrl('id'));

// Trouve le produit correspondant à l'identifiant
const produit = produits.find(p => p.id === produitId);
console.log(produit)


// Affiche les détails du produit
if (produit) {
    const produitDetailsDiv = document.getElementById('produit-details');
    produitDetailsDiv.innerHTML =
     `  <h2>${produit.id}</h2>
        <p>${produit.nom}<p>
         <img src=${produit.url}></img>
        <p>Prix : ${produit.prix} FCFA</p>
      
       
    `;
} else {
    // Si le produit n'est pas trouvé, affiche un message d'erreur
    document.getElementById('produit-details').innerHTML = '<p>Produit non trouvé.</p>';
}
if (produit) {
    const produitDetailsDiv = document.getElementById('description-div');
    produitDetailsDiv.innerHTML =
     `  
       <p>${produit.description}</p>
    
    `;
} else {
    // Si le produit n'est pas trouvé, affiche un message d'erreur
    document.getElementById('description-div').innerHTML = '<p>Produit non trouvé.</p>';
}

